// Emby Proxy - original-li
// co-auth-by MingTone
const CONFIG={
	PUBLIC_ORIGIN:"",	//填入你自己的反代域名，或者不填就是自动识别
	PROXY_PREFIX:"/emby",	//前缀（即客户端填写路径的/emby处）
	SIGNING_SECRET:"",	//防滥用签名，请使用你自己生成的随机字符串
	SIGNING_TTL_SECONDS:86400,
	SIGNING_CLOCK_SKEW_SECONDS:300,
	BACKENDS:{	//上游
		example:{		//此处example为上游名称，后续需要拼接到客户端路径内
			upstream:"https://example.com/emby"	//此处是上游url
		},
		exp:{			//同上
			upstream:"https://2.example.com/emby"
		}
	}
	/*
		比如你想要在客户端通过此反代链接example.com的emby，而你的反代域名为emby.726748.xyz，则需要这么填写：
			域名：emby.726748.xyz
			https: 启用
			端口：443
			路径：/emby/example
			
		exp则为
			域名：emby.726748.xyz
			https: 启用
			端口：443
			路径：/emby/exp
	*/
};
const I="__proxy",TS="__px_ts",EX="__px_exp",SG="__px_sig",HH=["connection","keep-alive","proxy-authenticate","proxy-authorization","te","trailers","transfer-encoding","upgrade"],AB=["/emby","/mediabrowser"],TX=/(?:application\/(?:json|xml|javascript|x-javascript|vnd\.apple\.mpegurl|x-mpegurl|dash\+xml)|application\/[^;]+\+json|text\/(?:plain|html|xml|vtt|json|javascript))/i,JX=/application\/json|application\/[^;]+\+json|text\/json/i,AX=/https?:\/\/[^\s"'<>\]\)]+/gi,AT=/__EMBY_ABS_(\d+)__/g,AP=/\/(?:(?:emby|mediabrowser|Videos|Audio|Items|Images|Users|Playback|PlaybackInfo|PlayQueues|LiveStreams|LiveTv|Sessions|System|Security|web|embywebsocket|socket|Subtitles|Artists|Albums|Genres|Shows|Movies|Channels|Collections|Persons|Studios|Games|Playlists|MusicGenres|Trailers|Packages|Startup|Search|Suggestions|Sync|Devices|UserViews|DisplayPreferences)\b[^\s"'<>\)]*)/g,SP=[/^\/Videos\/[^/]+\/(?:stream(?:\.[^/]+)?|original|download|file|master\.m3u8|main\.m3u8|live\.m3u8|subtitles\.m3u8)\b/i,/^\/Videos\/[^/]+\/hls1?\/[^/]+\/[^/]+(?:\.[^/]+)?$/i,/^\/Videos\/[^/]+\/[^/]+\/Subtitles\/[^/]+(?:\/[^/]+)?\/Stream\.[^/]+$/i,/^\/Audio\/[^/]+\/(?:stream(?:\.[^/]+)?|master\.m3u8|main\.m3u8|universal(?:\.[^/]+)?)\b/i,/^\/Audio\/[^/]+\/hls1\/[^/]+\/[^/]+(?:\.[^/]+)?$/i,/^\/LiveTv\/(?:LiveRecordings|LiveStreamFiles)\/[^/]+\/stream(?:\.[^/]+)?\b/i,/^\/(?:Playback|PlayQueues|LiveStreams|Videos\/ActiveEncodings)\b/i],SQ=["stream","hls","m3u8","mpd","manifest","playlist","transcod","segment","download","original","live"],BC=[/^\/Users\/(?:Authenticate(?:ByName|WithPolicy)?|Logout|ResetPassword|ForgotPassword)\b/i,/^\/Sessions\b/i,/^\/PlaybackInfo\b/i,/^\/Items\/[^/]+\/PlaybackInfo\b/i,/^\/Playback\b/i,/^\/PlayQueues\b/i,/^\/System\b/i,/^\/Security\b/i,/^\/Videos\/[^/]+\/(?:stream|original|download|file)\b/i,/^\/Videos\/[^/]+\/(?:master|main|live|subtitles)\.m3u8\b/i,/^\/Videos\/[^/]+\/hls1?\b/i,/^\/Videos\/ActiveEncodings\b/i,/^\/Audio\/[^/]+\/stream\b/i,/^\/Audio\/[^/]+\/(?:master|main)\.m3u8\b/i,/^\/Audio\/[^/]+\/hls1\b/i,/^\/Audio\/[^/]+\/universal(?:\.[^/]+)?\b/i,/^\/LiveTv\/(?:LiveRecordings|LiveStreamFiles)\/[^/]+\/stream(?:\.[^/]+)?\b/i,/^\/Items\/[^/]+\/download\b/i,/^\/Items\/[^/]+\/Images?/i,/^\/Images\b/i,/^\/Subtitle(?:s)?\b/i,/^\/web\b/i,/\/m3u8(?:\?|$)/i,/\/manifest(?:\?|$)/i,/\/transcod(?:\w*)/i],AH="Content-Type, Authorization, X-Emby-Authorization, X-Emby-Token, X-Emby-Client, X-Emby-Device-Id, X-Emby-Device-Name, X-Emby-Client-Version, X-MediaBrowser-Authorization, X-MediaBrowser-Token, X-MediaBrowser-Client, X-MediaBrowser-Device-Id, X-MediaBrowser-Device-Name, X-MediaBrowser-Client-Version, Range, Origin, Referer",EH="Content-Length, Content-Range, Content-Type, Accept-Ranges, X-Emby-Auth-Token, X-MediaBrowser-Auth-Token, Location, Content-Location";
function np(p){const s=String(p||"/").replace(/\/{2,}/g,"/");return s.startsWith("/")?s:`/${s}`}
function nb(p){p=np(p);return p==="/"?"/":p.replace(/\/+$/,"")||"/"}
function jp(l,r){const a=np(l),b=np(r);if(a==="/")return b;if(b==="/")return a;return`${a.replace(/\/+$/,"")}/${b.replace(/^\/+/,"")}`}
function pp(a,t){if(!a.length)return"/";const p=`/${a.join("/")}`;return t&&p!=="/"?`${p}/`:p}
function sp(p,pref){const path=np(p),base=nb(pref);if(base==="/")return path;if(path===base)return"/";if(path.startsWith(`${base}/`))return path.slice(base.length)||"/";return null}
function sa(p){let path=np(p),c=true;while(c&&path!=="/"){c=false;for(const q of AB){const n=nb(q);if(path===n){path="/";break}if(path.startsWith(`${n}/`)){path=path.slice(n.length)||"/";c=true;break}}}return path}
function nt(p,up){let path=np(p),c=true;while(c&&path!=="/"){c=false;const w=sk(path,up);if(w!==path){path=w;c=true}const x=sa(path);if(x!==path){path=x;c=true}}return path}
function sk(p,b){const path=np(p),base=nb(b);if(base==="/")return path;if(path===base)return"/";if(path.startsWith(`${base}/`))return path.slice(base.length)||"/";return path}
function nu(v){const r=String(v||"").trim();if(!r)return null;try{const u=new URL(/^https?:\/\//i.test(r)?r:`https://${r}`);if(!/^https?:$/i.test(u.protocol))return null;u.pathname=nb(u.pathname||"/");u.search="";u.hash="";return u}catch{return null}}
function gpo(){const r=String(CONFIG.PUBLIC_ORIGIN||"").trim();if(!r)return null;try{const u=new URL(r);u.pathname="/";u.search="";u.hash="";return u}catch{return null}}
function fh(v){return String(v||"").split(",")[0].trim()}
function cp(r){const v=r.headers.get("cf-visitor");if(!v)return"";try{const s=String(JSON.parse(v).scheme||"").toLowerCase();return s==="http"||s==="https"?s:""}catch{return""}}
function gpr(request){const o=new URL(request.url),c=gpo();if(c)return new URL(`${c.origin}${o.pathname}${o.search}`);const h=fh(request.headers.get("host"))||fh(request.headers.get("x-forwarded-host"))||fh(request.headers.get("x-original-host"))||fh(request.headers.get("x-host"))||o.host,pr0=fh(request.headers.get("x-forwarded-proto"))||cp(request)||o.protocol.replace(":",""),pr=pr0==="http"||pr0==="https"?`${pr0}:`:o.protocol;return new URL(`${pr}//${h}${o.pathname}${o.search}`)}
function gb(a){const r=CONFIG.BACKENDS&&CONFIG.BACKENDS[a];if(!r)return null;const u=nu(r.upstream);return u?{alias:a,upstream:u}:null}
const AC=new Map();function bab(a){let v=AC.get(a);if(v===undefined){v=jp(CONFIG.PROXY_PREFIX,a);AC.set(a,v)}return v}
function bap(u,a,p,s="",h=""){const x=new URL(u.origin);x.pathname=jp(bab(a),np(p));x.search=s;x.hash=h;return x}
function cup(t,b){if(t.origin!==b.upstream.origin)return false;const bp=nb(b.upstream.pathname||"/"),tp=np(t.pathname||"/");return bp==="/"||tp===bp||tp.startsWith(`${bp}/`)}
function esc(s){return String(s||"").replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}
function cda(t,a){const base=bab(a),rx=new RegExp(`${esc(base)}${esc(base)}(?=(?:/|\\?|#|$))`,"gi");let r=String(t||""),p="";while(r!==p){p=r;r=r.replace(rx,base)}return r}
function crb(s){return![101,204,205,304].includes(Number(s))}
function ibp(p,q){const path=np(p);if(BC.some(rx=>rx.test(path)))return true;for(const k of["api_key","apikey","token","access_token","deviceid","device_id","userid","user_id","playsessionid","sessionid","session_id"])if(q.has(k))return true;return false}
function isp(p,q){const path=nt(p,"/");if(SP.some(rx=>rx.test(path)))return true;if(/\/(?:m3u8|mpd|manifest)(?:$|\/)/i.test(path))return true;for(const[k,v]of q.entries()){const pair=`${k}=${v}`.toLowerCase();if(SQ.some(h=>pair.includes(h)))return true}return false}
function lra(s){s=String(s||"").trim();return s.startsWith("/")&&(/^\/(?:emby|mediabrowser|Videos|Audio|Items|Playback|PlaybackInfo|PlayQueues|LiveStreams|LiveTv|Sessions|Users\/|Images|web\/|embywebsocket|socket)/.test(s))}
function isu(v){return/^[a-z][a-z0-9+.-]*:\/\/?/i.test(String(v||"").trim())}
function gep(u){return u.port||(u.protocol==="http:"?"80":u.protocol==="https:"?"443":"")}
function cc(h,p){if(/^\/web\/|\/(?:css|js|woff2?|ttf|png|jp(?:e?)g|svg|ico|webp)(?:\?|$)/i.test(p))h.set("cache-control","public, max-age=86400, immutable");else if(/^\/(?:Items\/[^/]+\/Images|Images)\//i.test(p))h.set("cache-control","public, max-age=3600")}
function bfh(req,up,pr){const h=new Headers(req.headers),ws=String(h.get("upgrade")||"").toLowerCase()==="websocket";for(const n of HH){if(ws&&(n==="connection"||n==="upgrade"))continue;h.delete(n)}h.delete("host");h.delete("content-length");h.delete("x-forwarded-prefix");if(!ws){h.delete("connection");h.delete("upgrade")}const ip=req.headers.get("cf-connecting-ip");if(ip){h.set("x-real-ip",ip);h.set("x-forwarded-for",ip)}h.set("x-forwarded-host",pr.host);h.set("x-forwarded-proto",pr.protocol.replace(":",""));const au=h.get("authorization")||h.get("x-emby-authorization")||h.get("x-mediabrowser-authorization");if(au){h.set("authorization",au);h.set("x-emby-authorization",au);h.set("x-mediabrowser-authorization",au)}const or=h.get("origin");if(or){try{if(new URL(or).origin!==up.origin)h.set("origin",up.origin)}catch{h.set("origin",up.origin)}}const rf=h.get("referer");if(rf){try{const u=new URL(rf);u.protocol=up.protocol;u.host=up.host;h.set("referer",u.toString())}catch{h.set("referer",up.origin+"/")}}return h}
function cors(r){return{"Access-Control-Allow-Origin":r.headers.get("Origin")||r.headers.get("origin")||"*","Access-Control-Allow-Methods":"GET,HEAD,POST,PUT,PATCH,DELETE,OPTIONS","Access-Control-Allow-Headers":r.headers.get("Access-Control-Request-Headers")||AH,"Access-Control-Expose-Headers":EH,"Access-Control-Allow-Credentials":"true","Access-Control-Max-Age":"86400"}}
function ns(h){h.set("cache-control","no-store, private, max-age=0")}
function err(m,s=502){return new Response(String(m||"Upstream request failed"),{status:s,headers:{"content-type":"text/plain; charset=utf-8","cache-control":"no-store"}})}
function parse(P){const rel=sp(P,CONFIG.PROXY_PREFIX);if(rel===null)return null;const clean=np(rel),parts=clean.split("/").filter(Boolean);if(!parts.length)return{kind:"index"};let a=decodeURIComponent(parts[0]||""),rest=parts.slice(1);if(gb(a)){if(rest.length&&(rest[0]==="emby"||rest[0]==="mediabrowser"))rest=rest.slice(1)}else{const ac=a.split(":")[0];if(ac&&gb(ac)){a=ac;if(rest.length&&(rest[0]==="emby"||rest[0]==="mediabrowser"))rest=rest.slice(1)}}const be=gb(a);if(!be)return{kind:"unknown-backend",alias:a};if(rest[0]===I){const sch=rest[1]||"",host=rest[2]?decodeURIComponent(rest[2]):"",port=rest[3]||"",rp=rest.slice(4),dp=rp.length?`/${rp.join("/")}`:"/";if(!/^https?$/.test(sch)||!host||!/^[0-9]+$/.test(port))return{kind:"invalid-dynamic",alias:a};try{const dr=new URL(`${sch}://${host}:${port}`);dr.pathname="/";dr.search="";dr.hash="";return{kind:"dynamic",alias:a,backend:be,targetRoot:dr,targetPath:np(dp)}}catch{return{kind:"invalid-dynamic",alias:a}}}const bp=rest.length?`/${rest.join("/")}`:"/";return{kind:"backend",alias:a,backend:be,backendPath:bp}}
function bi(req){const prefix=nb(CONFIG.PROXY_PREFIX),aliases=Object.keys(CONFIG.BACKENDS||{}).sort(),u=gpr(req).origin;return new Response(JSON.stringify({ok:true,prefix,publicOrigin:u,backends:aliases,examples:aliases.map(a=>`${u}${prefix}/${a}`)},null,2),{status:200,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}})}
const TE=new TextEncoder();let KP=null;function now(){return Math.floor(Date.now()/1000)}
function key(){return KP||(KP=crypto.subtle.importKey("raw",TE.encode(String(CONFIG.SIGNING_SECRET||"")),{name:"HMAC",hash:"SHA-256"},false,["sign"]))}
const HX=[];for(let i=0;i<256;i++)HX[i]=i.toString(16).padStart(2,"0");function hex(b){const B=new Uint8Array(b);let o="";for(let i=0;i<B.length;i++)o+=HX[B[i]];return o}
function tse(a,b){const l=String(a||""),r=String(b||""),m=Math.max(l.length,r.length);let d=l.length^r.length;for(let i=0;i<m;i++)d|=(l.charCodeAt(i)||0)^(r.charCodeAt(i)||0);return d===0}
function cq(q,omit=[]){const O=new Set(omit.map(String)),p=[];for(const[k,v]of q.entries()){if(!O.has(k))p.push([k,v])}p.sort((a,b)=>a[0]===b[0]?(a[1]<b[1]?-1:a[1]>b[1]?1:0):a[0]<b[0]?-1:1);return p.map(([k,v])=>`${encodeURIComponent(k)}=${encodeURIComponent(v)}`).join("&")}
function bs(u,omit=[SG]){const q=cq(u.searchParams,omit);return q?`${u.origin}${u.pathname}?${q}`:`${u.origin}${u.pathname}`}
async function sig(u){return hex(await crypto.subtle.sign("HMAC",await key(),TE.encode(bs(u,[SG]))))}
async function ads(pu){const u=new URL(pu.toString()),n=now();u.searchParams.delete(TS);u.searchParams.delete(EX);u.searchParams.delete(SG);u.searchParams.set(TS,String(n));u.searchParams.set(EX,String(n+Number(CONFIG.SIGNING_TTL_SECONDS||86400)));u.searchParams.set(SG,await sig(u));return u}
async function vdr(req){const pu=gpr(req),tr=pu.searchParams.get(TS),er=pu.searchParams.get(EX),sr=pu.searchParams.get(SG);if(!tr||!er||!sr)return{ok:false,status:403,message:"Missing signature"};if(!/^\d+$/.test(tr)||!/^\d+$/.test(er))return{ok:false,status:403,message:"Invalid timestamp"};const ts=Number(tr),ex=Number(er),n=now(),ttl=Number(CONFIG.SIGNING_TTL_SECONDS||86400),sk=Number(CONFIG.SIGNING_CLOCK_SKEW_SECONDS||300);if(!Number.isFinite(ts)||!Number.isFinite(ex)||ex<ts)return{ok:false,status:403,message:"Invalid timestamp"};if(ex-ts>ttl+sk)return{ok:false,status:403,message:"TTL exceeded"};if(ts>n+sk)return{ok:false,status:403,message:"Not yet valid"};if(ex<n-sk)return{ok:false,status:403,message:"Expired"};const u=new URL(pu.toString());u.searchParams.delete(SG);if(!tse(sr,await sig(u)))return{ok:false,status:403,message:"Signature mismatch"};return{ok:true,publicUrl:pu}}
async function bdp(ru,a,t){const pu=new URL(ru.origin),sch=t.protocol.replace(":",""),host=encodeURIComponent(t.hostname),port=gep(t),tp=np(t.pathname||"/"),prefix=nb(CONFIG.PROXY_PREFIX).replace(/^\/+/,""),parts=[prefix,encodeURIComponent(a),I,sch,host,port];if(tp!=="/")parts.push(...tp.replace(/^\/+/,"").split("/").filter(Boolean));pu.pathname=`/${parts.join("/")}`;pu.search=t.search;pu.hash=t.hash;return ads(pu)}
async function rru(ru,req,b,opt={}){const ap=!!opt.asPathOnly,fa=!!opt.forceAbsolute,st=isp(ru.pathname,ru.searchParams);let pu;if(cup(ru,b)){pu=bap(req,b.alias,nt(ru.pathname,b.upstream.pathname),ru.search,ru.hash)}else pu=await bdp(req,b.alias,ru);return ap&&!st&&!fa?pu.pathname+pu.search+pu.hash:pu.toString()}
async function rau(v,req,b,base,opt={}){try{const ru=new URL(String(v||""),base);return/^https?:$/i.test(ru.protocol)?await rru(ru,req,b,opt):String(v)}catch{return String(v)}}
function srj(k,v){const lk=String(k||"").toLowerCase(),s=String(v||"");if(isu(s))return true;if(!s.startsWith("/"))return false;if(lra(s))return true;if(lk.includes("url")||lk.endsWith("uri")||lk.includes("link")||lk==="path"||lk.endsWith("path"))return lra(s);return false}
async function rjo(x,req,b,base,k=""){if(Array.isArray(x)){const o=[];for(const i of x)o.push(await rjo(i,req,b,base,k));return o}if(x&&typeof x==="object"){const o={};for(const[k2,v]of Object.entries(x))o[k2]=await rjo(v,req,b,base,k2);return o}if(typeof x==="string")return srj(k,x)?rau(x,req,b,base,{asPathOnly:true}):cda(x,b.alias);return x}
async function ar(src,rx,fn){const s=String(src||""),fl=rx.flags.includes("g")?rx.flags:rx.flags+"g",r=new RegExp(rx.source,fl),C=[],P=[];let L=0,m;while((m=r.exec(s))){C.push(s.slice(L,m.index));P.push(fn(m[0],m));L=m.index+m[0].length;if(m[0]==="")r.lastIndex++}C.push(s.slice(L));const R=await Promise.all(P);let o=C[0];for(let i=0;i<R.length;i++)o+=R[i]+C[i+1];return o}
async function rpt(txt,req,b,base){const n=String(txt||"").replace(/\\\//g,"/"),am=[],rx=new RegExp(AX.source,AX.flags);let m;while((m=rx.exec(n)))am.push(m[0]);const aw=await Promise.all(am.map(u=>rau(u,req,b,base,{asPathOnly:true})));let i=0;const wt=n.replace(AX,()=>`__EMBY_ABS_${i++}__`),wr=await ar(wt,AP,async m=>m.includes("__EMBY_ABS_")?m:rau(m,req,b,base,{asPathOnly:true}));return cda(wr.replace(AT,(t,j)=>{const i=Number(j);return Number.isFinite(i)&&aw[i]?aw[i]:t}),b.alias)}
async function rr(res,req,up,b){const h=new Headers(res.headers);for(const n of HH)h.delete(n);h.delete("content-length");h.delete("content-encoding");h.delete("transfer-encoding");h.delete("server");h.delete("x-powered-by");h.set("access-control-allow-origin",req.origin);h.set("access-control-allow-credentials","true");h.set("access-control-expose-headers",EH);h.set("vary",[h.get("vary"),"Origin"].filter(Boolean).join(", "));const loc=h.get("location");if(loc)h.set("location",await rau(loc,req,b,up,{forceAbsolute:res.status>=300&&res.status<400}));const cl=h.get("content-location");if(cl)h.set("content-location",await rau(cl,req,b,up,{forceAbsolute:true}));const rf=h.get("refresh");if(rf)h.set("refresh",await ar(String(rf),/\burl\s*=\s*([^;]+)/i,async(m,f)=>`url=${await rau(String(f[1]||"").trim().replace(/^['"]|['"]$/g,""),req,b,up,{forceAbsolute:true})}`));const sc=typeof res.headers.getSetCookie==="function"?res.headers.getSetCookie():[];if(sc.length){h.delete("set-cookie");for(const c of sc){const ps=String(c||"").split(/;\s*/).filter(Boolean);if(!ps.length)continue;const rw=[ps[0]];let hp=false;for(let i=1;i<ps.length;i++){const p=ps[i],lo=p.toLowerCase();if(lo.startsWith("domain="))continue;if(lo.startsWith("path=")){rw.push(`Path=${bab(b.alias)}`);hp=true}else rw.push(p)}if(!hp)rw.push(`Path=${bab(b.alias)}`);h.append("set-cookie",rw.join("; "))}}cc(h,up.pathname);if(!TX.test(res.headers.get("content-type")||""))return new Response(crb(res.status)?res.body:null,{status:res.status,statusText:res.statusText,headers:h});if(!crb(res.status))return new Response(null,{status:res.status,statusText:res.statusText,headers:h});const ct=h.get("content-type")||"",body=await res.text();if(JX.test(ct)){try{return new Response(JSON.stringify(await rjo(JSON.parse(body),req,b,up)),{status:res.status,statusText:res.statusText,headers:h})}catch{}}return new Response(await rpt(body,req,b,up),{status:res.status,statusText:res.statusText,headers:h})}
async function ppr(request,p){let req;if(p.kind==="dynamic"){const v=await vdr(request);if(!v.ok)return err(v.message,v.status||403);req=v.publicUrl}else req=gpr(request);const q=new URLSearchParams(req.search);if(p.kind==="dynamic"){q.delete(TS);q.delete(EX);q.delete(SG)}let root,path;if(p.kind==="dynamic"){root=p.targetRoot;path=p.targetPath}else{root=p.backend.upstream;path=nt(p.backendPath,p.backend.upstream.pathname)}const up=new URL(root.toString());up.pathname=p.kind==="dynamic"?np(path):jp(root.pathname,path);up.search=q.toString();const init={method:request.method,headers:bfh(request,up,req),redirect:"manual"};if(request.method!=="GET"&&request.method!=="HEAD")init.body=request.body;let ur;try{ur=await fetch(up.toString(),init)}catch{return err("Upstream request failed",502)}if(!TX.test(ur.headers.get("content-type")||"")&&ur.status<300){const sh=new Headers(ur.headers);for(const n of HH)sh.delete(n);sh.delete("server");sh.delete("x-powered-by");sh.set("access-control-allow-origin",req.origin);sh.set("access-control-allow-credentials","true");sh.set("vary",[sh.get("vary"),"Origin"].filter(Boolean).join(", "));cc(sh,up.pathname);return new Response(ur.body,{status:ur.status,statusText:ur.statusText,headers:sh})}const out=await rr(ur,req,up,p.backend),bp=p.kind==="dynamic"?up.pathname:path;if(ibp(bp,q)){const h=new Headers(out.headers);ns(h);return new Response(crb(out.status)?out.body:null,{status:out.status,statusText:out.statusText,headers:h})}return out}
export default{async fetch(request){try{const p=parse(new URL(request.url).pathname);if(request.method==="OPTIONS"){if(p!==null)return new Response(null,{status:204,headers:cors(request)});return fetch(request)}if(p===null)return fetch(request);if(p.kind==="index")return fetch(request);if(p.kind==="unknown-backend")return err(`Unknown backend: ${p.alias}`,404);if(p.kind==="invalid-dynamic")return err("Invalid dynamic upstream path",400);return await ppr(request,p)}catch(e){return err(`Runtime error: ${e?.message||String(e)}`,500)}}};
